export class SyncBatchEntryModel {
Amount: number= 0;
Amount_currency: string = '';
Approved: string = '';
ApproverName: string = '';
BatchUserName: string = '';
Batched: string = '' ;
BatchedByName: string = '';
CashAccount: string = '';
ClerkName: string = '';
Comment: string = '';
CompanyName: string = '';
CompanyReviewerName: string = '';
CssID: number= 0;
Deleted: any;
DeletedByName: string= '';
Description: string = '';
DueDate: Date;
Expedited: any;
ExpeditedByName: string = '';
InvApprovalDate: Date;
InvoiceApproverName: string = '';
InvoiceDate: Date;
InvoiceDestributions: Array<any>= [];
InvoiceID: number= 0;
InvoiceNumber: string = '';
InvoiceState: number= 0;
IsApprovalRequired: boolean;
IsBatche: boolean;
IsDeleteInvoice: boolean;
IsExpdite: boolean;
IsReviewvalRequired: boolean;
IsSubmitForApprovalRequired: boolean;
Job: string = '';
JobCategory: string = '';
RejectedByName: string = '';
RejectionComment: string = '';
Reviewed: string = '';
ReviewerName: string = '';
SLCashAccount: string = '';
Status: string = '';
SyncEnabled: boolean;
UpdatedByName: string = '';
VendorKey: string = '';
VendorName: string = '';
account_id: number= 0;
approver_id: number= 0;
batched_by_id: number= 0;
clerk_id: number= 0;
company_id: number= 0;
deleted_by_id: number= 0;
expedited_by_id: number= 0;
job_category_id: number= 0;
job_id: number= 0;
purchase_order_id: number= 0;
rejected_by_id: number= 0;
reviewer_id: number= 0;
sync_batch_id: number= 0;
type: string = '';
updated_by_id: number= 0;
vendor_id: number= 0;
}
export class SyncBatchModel {
                id: number = 0;
                Comment: string = '';
                SyncBatcheInvoices: Array<any>= [];
            }
