export class CompanyModel {
  ActivationLink: string= '';
  Active: boolean;
  ApprovalCriteriaCount: number= 0;
  CompanyCount: number= 0;
  CompanyID: number= 0;
  FundCount: number= 0;
  InvoiceCount: number= 0;
  LedgerAccountCount: number= 0;
  Name: string= '';
  number: string= '';
  PDFCount: number= 0;
  PurchaseOrderCount: number= 0;
  RowNumber: number= 0;
  Sync: string= '';
  ToolTipTypeText: string= '';
  VendorCount: number= 0;
  account_id: number= 0;
  APDescription: string= '';
  AccountName: string= '';
  AchSetupCount: string= '';
  CashAccount1Description: string= '';
  CashAccount2Description: string= '';
  CashAccount3Description: string= '';
  CashAccount4Description: string= '';
  CompNameOnChecks: string= '';
  CompanyName: string= '';
  CompanyNameCheck1: string= '';
  CompanyNameCheck2: string= '';
  DbName: string= '';
  DiscountDescription: string= '';
  OneRec: string= '';
  POCount: number= 0;
  PdfFolderPath: string= '';
  PrePaidDescription: string= '';
  ShowAcctsOnStub: string= '';
  ShowPropOnStub: string= '';
  SyncEnabled: string= '';
  ap_account_id: string= '';
  approve_invoice_role_id: number= 0;
  approver_override_role_id: number= 0;
  batch_invoice_role_id: number= 0;
  cash_account_1_id: string= '';
  cash_account_2_id: string= '';
  cash_account_3_id: string= '';
  cash_account_4_id: string= '';
  create_invoice_role_id: number= 0;
  delete_invoice_role_id: number= 0;
  discount_account_id: string= '';
  pre_paid_account_id: string= '';
  review_invoice_role_id: number= 0;
  type: string= '';
  view_invoice_role_id: number= 0;
  status:any;
}

